classdef ScriptsCoverageTest < matlab.unittest.TestCase
    % ScriptsCoverageTest
    % Executes every standalone script in scripts/ to register code coverage.
    %
    % Design decisions
    % ----------------
    % 1. safeRun()  – scripts start with `clear`, which wipes the caller workspace.
    %    Wrapping run() in a static helper creates a separate stack frame so that
    %    `clear` only affects the helper's scope, leaving testCase intact.
    %
    % 2. cd(scriptsDir) in setup – some scripts use '../logs' (relative to scripts/)
    %    while others use 'logs' (relative to CWD). Running from scripts/ unifies both:
    %      '../logs'  →  <repo>/logs/       (where we put mock CSV)
    %      'logs'     →  <repo>/scripts/logs (where we also put a copy)
    %
    % 3. sendMockTCPPacket.m – static method callbacks can't be resolved from a
    %    timer's async context.  A plain function file on the path works fine.

    properties
        RootDir            % absolute path to repo root
        OrigDir            % CWD before each test (restored on teardown)
        MockRootCSV        % <repo>/logs/AQI_Log_CoverageMock.csv
        MockScriptsCSV     % <repo>/scripts/logs/AQI_Log_CoverageMock.csv
    end

    % -----------------------------------------------------------------------
    methods(TestMethodSetup)
        function setupData(testCase)
            testCase.RootDir = fullfile(fileparts(mfilename('fullpath')), '..');

            % Put all src + scripts + tests on the path BEFORE cd so timer
            % callbacks (sendMockTCPPacket) can resolve functions from scripts/
            addpath(fullfile(testCase.RootDir, 'src'));
            addpath(fullfile(testCase.RootDir, 'scripts'));
            addpath(fullfile(testCase.RootDir, 'tests'));

            % --- create mock log files in BOTH expected locations ---
            rootLogs    = fullfile(testCase.RootDir, 'logs');
            scriptsLogs = fullfile(testCase.RootDir, 'scripts', 'logs');
            if ~exist(rootLogs,    'dir'), mkdir(rootLogs);    end
            if ~exist(scriptsLogs, 'dir'), mkdir(scriptsLogs); end

            T = ScriptsCoverageTest.buildMockTable(120);

            testCase.MockRootCSV    = fullfile(rootLogs,    'AQI_Log_CoverageMock.csv');
            testCase.MockScriptsCSV = fullfile(scriptsLogs, 'AQI_Log_CoverageMock.csv');
            writetable(T, testCase.MockRootCSV);
            writetable(T, testCase.MockScriptsCSV);

            % --- ensure models/ dirs exist (some scripts save there) ---
            rootModels    = fullfile(testCase.RootDir, 'models');
            scriptsModels = fullfile(testCase.RootDir, 'scripts', 'models');
            if ~exist(rootModels,    'dir'), mkdir(rootModels);    end
            if ~exist(scriptsModels, 'dir'), mkdir(scriptsModels); end

            % Seed a dummy trainedModel so AirQualitySystem constructor won't warn
            for mpath = {fullfile(rootModels,'trainedModel.mat'), ...
                         fullfile(scriptsModels,'trainedModel.mat')}
                if ~exist(mpath{1}, 'file')
                    MLModel = 1; FeatureMu = zeros(1,7); FeatureSigma = ones(1,7); %#ok<NASGU>
                    save(mpath{1}, 'MLModel', 'FeatureMu', 'FeatureSigma');
                end
            end

            % Env vars required by socket_intelligence_dashboard
            setenv('MATLAB_PORT', '5056');
            setenv('PI_IP',       '127.0.0.1');
            setenv('PI_USER',     'testuser');
            setenv('PI_PASS',     'testpass');
            setenv('SERIAL_PORT', '/dev/ttyUSB0');
            setenv('BAUD_RATE',   '9600');

            % Change to scripts/ so relative paths resolve correctly, then
            % save original dir for teardown
            testCase.OrigDir = cd(fullfile(testCase.RootDir, 'scripts'));
        end
    end

    % -----------------------------------------------------------------------
    methods(TestMethodTeardown)
        function teardownData(testCase)
            cd(testCase.OrigDir);
            if exist(testCase.MockRootCSV,    'file'), delete(testCase.MockRootCSV);    end
            if exist(testCase.MockScriptsCSV, 'file'), delete(testCase.MockScriptsCSV); end
            % Remove any CSVs generated by scripts during this test (e.g. NoveltyReport)
            % to prevent vertcat column-count mismatches in subsequent tests
            generatedReports = dir(fullfile(testCase.RootDir, 'logs', '*.csv'));
            for k = 1:numel(generatedReports)
                if ~strcmp(generatedReports(k).name, 'AQI_Log_CoverageMock.csv')
                    delete(fullfile(generatedReports(k).folder, generatedReports(k).name));
                end
            end
            generatedScriptReports = dir(fullfile(testCase.RootDir, 'scripts', 'logs', '*.csv'));
            for k = 1:numel(generatedScriptReports)
                if ~strcmp(generatedScriptReports(k).name, 'AQI_Log_CoverageMock.csv')
                    delete(fullfile(generatedScriptReports(k).folder, generatedScriptReports(k).name));
                end
            end
            close all force;
        end
    end

    % -----------------------------------------------------------------------
    methods(Test)

        function testAdaptiveIntelligenceSystem(testCase)
            ScriptsCoverageTest.safeRun('adaptive_intelligence_system.m');
            testCase.verifyTrue(true);
        end

        function testBacktestForecaster(testCase)
            ScriptsCoverageTest.safeRun('backtest_forecaster.m');
            testCase.verifyTrue(true);
        end

        function testCompareFilterPerformance(testCase)
            ScriptsCoverageTest.safeRun('compare_filter_performance.m');
            testCase.verifyTrue(true);
        end

        function testCrossValidateSystem(testCase)
            ScriptsCoverageTest.safeRun('cross_validate_system.m');
            testCase.verifyTrue(true);
        end

        function testDetectNovelty(testCase)
            ScriptsCoverageTest.safeRun('detect_novelty.m');
            testCase.verifyTrue(true);
        end

        function testEvaluateModelPerformance(testCase)
            ScriptsCoverageTest.safeRun('evaluate_model_performance.m');
            testCase.verifyTrue(true);
        end

        function testExplainModel(testCase)
            ScriptsCoverageTest.safeRun('explain_model.m');
            testCase.verifyTrue(true);
        end

        function testFeatureEngineering(testCase)
            ScriptsCoverageTest.safeRun('feature_engineering.m');
            testCase.verifyTrue(true);
        end

        function testSourceDetectionML(testCase)
            ScriptsCoverageTest.safeRun('source_detection_ml.m');
            testCase.verifyTrue(true);
        end

        function testTrainFromRawLogs(testCase)
            ScriptsCoverageTest.safeRun('train_from_raw_logs.m');
            testCase.verifyTrue(true);
        end

        function testLiveIntelligenceDashboard(testCase)
            % Close all figures after 1.5 s to break the while-ishghandle loop
            t = timer('ExecutionMode', 'singleShot', 'StartDelay', 1.5, ...
                      'TimerFcn', @(~,~) close('all','force'));
            start(t);
            ScriptsCoverageTest.safeRun('live_intelligence_dashboard.m');
            if isvalid(t), stop(t); delete(t); end
            testCase.verifyTrue(true);
        end

        function testSocketIntelligenceDashboard(testCase)
            port = str2double(getenv('MATLAB_PORT'));

            % Timer 1: inject a JSON packet once server is up
            inject_t = timer('ExecutionMode', 'singleShot', 'StartDelay', 0.8, ...
                             'TimerFcn', @(~,~) sendMockTCPPacket('127.0.0.1', port));

            % Timer 2: close the figure to exit the while loop
            close_t  = timer('ExecutionMode', 'singleShot', 'StartDelay', 2.5, ...
                             'TimerFcn', @(~,~) close('all','force'));

            start(inject_t);
            start(close_t);

            ScriptsCoverageTest.safeRun('socket_intelligence_dashboard.m');

            for t = [inject_t, close_t]
                if isvalid(t), stop(t); delete(t); end
            end
            testCase.verifyTrue(true);
        end

    end

    % -----------------------------------------------------------------------
    methods(Static)

        function safeRun(scriptName)
            % Run script in its own stack-frame so that the script's `clear`
            % command does not wipe the calling test-method's `testCase` variable.
            try
                run(scriptName);
            catch ME
                fprintf('ERROR EXECUTING SCRIPT %s:\n%s\n', scriptName, ME.message);
                rethrow(ME);
            end
        end

        function T = buildMockTable(n)
            % Build a mock AQI_Log CSV with all columns used by every script.
            rng(0);
            Time_s        = (1:n)';
            Timestamp     = string(datestr(now - linspace(1,0,n)', 'yyyy-mm-dd HH:MM:SS'));
            PM25          = max(5, 20 + 15*sin(linspace(0,4*pi,n)') + 3*randn(n,1));
            % Inject high-PM2.5 spikes so source_detection_ml gets multiple classes
            PM25(30:40)   = 60;
            PM25(70:80)   = 55;
            PM10          = PM25 .* 1.3 + 5*abs(randn(n,1)) + 10;
            PM25Filtered  = PM25 + 0.5*randn(n,1);
            PM10Filtered  = PM10 + 0.5*randn(n,1);
            pm25          = PM25;   % lower-case aliases for older scripts
            pm10          = PM10;
            Features_7D   = rand(n, 7);
            Forecast_PM25 = PM25 + randn(n,1)*2;
            NoveltyScores = rand(n,1) * 0.5;
            NoveltyData   = false(n,1);

            % Labels: mostly Clean, with several pollution windows
            Source = repmat("Clean", n, 1);
            Source(20:30)  = "Traffic";
            Source(55:70)  = "Dust";
            Source(85:95)  = "Combustion (cooking / smoke)";

            Advice = repmat("Air is clean", n, 1);
            Advice(20:30)  = "Moderate - consider ventilation";
            Advice(55:70)  = "PRE-EMPTIVE WARNING: Forecasted Spike - Close Windows Now";
            Advice(85:95)  = "Unhealthy - open window / reduce activity";

            T = table(Time_s, Timestamp, PM25, PM10, PM25Filtered, PM10Filtered, ...
                      pm25, pm10, Features_7D, Forecast_PM25, ...
                      NoveltyScores, NoveltyData, Source, Advice);
        end

    end
end
